### ISSUE TITLE
For stacked bar ?

### ISSUE THREAD

**Issue by kocil** [datavisyn/chartjs-scale-hierarchical#4]
Hello,
This is really great. 
I came here from the https://github.com/chartjs/Chart.js/issues/4946.
So the remaining issue, how to use it for a stacked bar chart ?

Thank you very much.

**Comment by sgratzl** [comment]
just like a regular stacked bar chart. Define two dataset-trees and specify `stacked: true`. Since the hierarchical scale is based on the regular categorical one, it works out of the box. 

see
https://codepen.io/sgratzl/pen/WKNrOJ?editors=0010

![image](https://user-images.githubusercontent.com/4129778/42495107-6c42843c-8422-11e8-86a4-c0cc4b43ba0d.png)

**Comment by kocil** [comment]
Perfect 👍 

Thank you very much
